carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_or_delete/<int:product_id>/<int:cart_item_id>/', views.remove_or_delete, name='remove_or_delete'),
    path('delete_cart/<int:product_id>/<int:cart_item_id>/', views.delete_cart, name='delete_cart'), 
    path('checkout/', views.checkout, name='checkout'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from stores import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('store/', include('stores.urls')),  
    path('cart/', include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('currencies/', include('currencies.urls')),
    path('selectcurrency', views.selectcurrency, name='selectcurrency'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
    path('savelangcur', views.savelangcur, name='savelangcur'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

stores/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_details, name='product_details'),
    path('search', views.search, name='search'), 
    path('terms', views.terms, name='terms'),
    path('delivery', views.delivery, name='delivery'),
    path('refund', views.refund, name='refund'),
    path('privacy', views.privacy, name='privacy'),
    path('contact', views.contact, name='contact')
]

carts/models.py
from django.db import models
from stores.models import Product, Variation
from accounts.models import Account

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

stores/models.py
from django.db import models
from category.models import Category
from accounts.models import Account

from django.db.models import Avg, Count
from django.urls import reverse


class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    images = models.ImageField(upload_to='pictures/products')
    alt_images = models.ImageField(upload_to='pictures/products', blank=True)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    modified_date=models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('product_details', args=[self.category.url, self.slug])

    def __str__(self):
        return self.product_name

    def average_review(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
        avg = 0
        if reviews['average'] is not None:
            avg = float(reviews['average'])
        return avg

    def review_count(self):
        reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(total=Count('id'))
        total = 0
        if reviews['total'] is not None:
            total = int(reviews['total'])
        return total


class VariationManager(models.Manager):  
    def colors(self):
        return super(VariationManager, self).filter(variation_category='color', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)


variation_category = (
    ('color', 'color'),
    ('size', 'size'),
)


class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value


class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank=True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.subject


class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/gallery/')

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'


class BannerGallery(models.Model):
    subtitle = models.TextField(max_length=500, blank=True)
    heading = models.TextField(max_length=500, blank=True)
    description = models.TextField(max_length=500, blank=True)
    image = models.ImageField(upload_to='banner/images', max_length=255)

    def __str__(self):
        return self.heading

    class Meta:
        verbose_name = 'bannergallery'
        verbose_name_plural = 'banner gallery'


class ContactPage(models.Model):
    email = models.EmailField(max_length=500)
    subject = models.CharField(max_length=500)
    message = models.TextField(max_length=500)

stores/forms.py
from django import forms
from .models import ReviewRating, ContactPage


class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']


class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactPage
        fields = ['email', 'subject', 'message']

carts/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from stores.models import Product, Variation
from .models import Cart, CartItem
from django.contrib.auth.decorators import login_required
from currencies.models import Currency


def cart(request):
    if not request.session.get('currency'):
        currency = Currency.objects.filter(code="KZT").first()
        if not currency:
            request.session['currency'] = 'KZT'
        else:
            request.session['currency'] = currency.code

    currency_code = request.session.get('currency', 'KZT')
    currency = Currency.objects.filter(code=currency_code).first()

    if not currency:
        currency = Currency.objects.filter(code="KZT").first()
        request.session['currency'] = 'KZT'

    cart_items = Cart.objects.filter(user=request.user)  
    total = sum([item.quantity * item.product.price for item in cart_items])
    tax = total * 0.12 
    grand_total = total + tax

    context = {
        'cart_items': cart_items,
        'total': total,
        'tax': tax,
        'grand_total': grand_total,
        'currency': currency, 
    }

    return render(request, 'cart.html', context)

def _cart_id(request):
    cart = request.session.session_key  
    if not cart:
        cart = request.session.create() 
    return cart

@csrf_exempt
def add_to_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    product_variation = []

    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]
            try:
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
            except:
                pass

    if current_user.is_authenticated:
        cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            existing_variation_list, id_list = [], []

            for item in cart_item:
                existing_variation_list.append(list(item.variations.all()))
                id_list.append(item.id)

            if product_variation in existing_variation_list:
                index = existing_variation_list.index(product_variation)
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                new_cart_item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0:
                    new_cart_item.variations.clear()
                    new_cart_item.variations.add(*product_variation)
                new_cart_item.save()
        else:
            new_cart_item = CartItem.objects.create(product=product, quantity=1, user=current_user)
            if len(product_variation) > 0:
                new_cart_item.variations.clear()
                new_cart_item.variations.add(*product_variation)
            new_cart_item.save()

        return redirect('cart')

    else:
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

        cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            existing_variation_list, id_list = [], []

            for item in cart_item:
                existing_variation_list.append(list(item.variations.all()))
                id_list.append(item.id)

            if product_variation in existing_variation_list:
                index = existing_variation_list.index(product_variation)
                item_id = id_list[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                new_cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0:
                    new_cart_item.variations.clear()
                    new_cart_item.variations.add(*product_variation)
                new_cart_item.save()
        else:
            new_cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
            if len(product_variation) > 0:
                new_cart_item.variations.clear()
                new_cart_item.variations.add(*product_variation)
            new_cart_item.save()

        return redirect('cart')

def remove_or_delete(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')

def delete_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        cart_item.delete()
    except:
        pass
    return redirect('cart')

def cart(request, tax=0, grand_total=0, total=0, quantity=0, cart_items=None):
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/cart.html', context)

@login_required(login_url='login')
def checkout(request, tax=0, grand_total=0, total=0, quantity=0, cart_items=None):
    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

        tax = (2 * total) / 100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total': total,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
    }
    return render(request, 'store/checkout.html', context)

templates/store/contact.html
{% extends 'base_two.html' %}
{% load static %}

{% block content %}

    <div class="breadcrumb-section">
        <div class="breadcrumb-wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-12 d-flex justify-content-between justify-content-md-between  align-items-center flex-md-row flex-column">
                         <h3 class="breadcrumb-title">{{ title }}</h3>
                        <div class="breadcrumb-nav">
                            <nav aria-label="breadcrumb">
                                <ul>
                                    <li><a href="/">Басты бет</a></li>
                                    <li class="active" aria-current="page">Ережелер мен шарттар</li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> 

    <div class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="contact-details-wrapper section-top-gap-100" data-aos="fade-up"  data-aos-delay="0">
                        <div class="contact-details">
                            <div class="contact-details-single-item">
                                <div class="contact-details-icon">
                                    <i class="fa fa-phone"></i>
                                </div>
                                <div class="contact-details-content contact-phone">
                                    <a href="tel:7(778)083-60-06">7(778)083-60-06</a>
                                </div>
                            </div> 
                            <div class="contact-details-single-item">
                                <div class="contact-details-icon">
                                    <i class="fa fa-globe"></i>
                                </div>
                                <div class="contact-details-content contact-phone">
                                    <a href="mailto:urname@email.com">support@ernurautoemporium.com</a>
                                    <a href="http://www.yourwebsite.com">ernurautoemporium.com</a>
                                </div>
                            </div> 
                            <div class="contact-details-single-item">
                                <div class="contact-details-icon">
                                    <i class="fa fa-map-marker"></i>
                                </div>
                                <div class="contact-details-content contact-phone">
                                    <span>Auto parts store in Atyrau, Kazakhstan, Kazakhstan business registration</span>
                                    <span>GUW - 000060 | Ernur Auto Emporium</span>
                                </div>
                            </div> 
                        </div>
                        <div class="contact-social">
                            <h4>Бізге жазылыңыз</h4>
                            <ul>
                                <li><a href="https://www.instagram.com/dapperautoparts/"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div> 
                    </div> 
                </div>
                <div class="col-lg-8">
                    <div class="contact-form section-top-gap-100" data-aos="fade-up"  data-aos-delay="200">
                        <h3>Бізбен хабарласу</h3>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="default-form-box mb-20">
                                        <label for="contact-email">Электрондық пошта</label>
                                        <input name="email" type="email" id="contact-email">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="default-form-box mb-20">
                                        <label for="contact-subject">Тақырыбы</label>
                                        <input name="subject" type="text" id="contact-subject">
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="default-form-box mb-20">
                                        <label for="contact-message">Сіздің хабарламаңыз</label>
                                        <textarea name="message" id="contact-message" cols="30" rows="10"></textarea>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <button class="contact-submit-btn" type="submit">ЖІБЕРУ</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/store/product_details.html
{% extends 'base_two.html' %}
{% load static %}

{% block content %}

<style>
.product-add-to-cart-btnx {
    display: inline-block;
    font-size: 16px;
    margin-left: 0px;
    background: #ea1c26;
    height: 42px;
    line-height: 42px;
    text-transform: capitalize;
    min-width: 200px;
    text-align: center;
    color: #FFF;
    border-radius: 3px;
    margin-top: 7px;
    font-weight: 500;
}
@media (min-width: 768px){
    .product-add-to-cart-btnx {
        min-width: 200px;
    }
}
@media (min-width: 992px){
    .product-add-to-cart-btnx {
        min-width: 270px;
    }
}
.product-add-to-cart-btnx:hover {
    background: #666;
}
</style>

<div class="breadcrumb-section">
    <div class="breadcrumb-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-12 d-flex justify-content-between justify-content-md-between align-items-center flex-md-row flex-column">
                    <h3 class="breadcrumb-title">Бірыңғай тауар</h3>
                    <div class="breadcrumb-nav">
                        <nav aria-label="breadcrumb">
                            <ul>
                                <li><a href="/">Басты бет</a></li>
                                <li class="active" aria-current="page">Тауар</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="product-details-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="product-details-gallery-area" data-aos="fade-up" data-aos-delay="0">
                    <div class="product-large-image product-large-image-horaizontal">
                        {% for i in product_gallery %}
                        <div class="product-image-large-single zoom-image-hover">
                            <img src="{{ i.image.url }}" alt="">
                        </div>
                        {% endfor %}
                    </div>
                    <div class="product-image-thumb product-image-thumb-horizontal pos-relative">
                        {% for i in product_gallery %}
                        <div class="product-image-thumb-single">
                            <img class="img-fluid" src="{{ i.image.url }}" alt="">
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <form style="display:contents" action="{% url 'add_to_cart' single_product.id %}" method="POST">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="product-details-content-area" data-aos="fade-up" data-aos-delay="200">
                        <div class="product-details-text">
                            <h4 class="title">{{ single_product.product_name }}</h4>
                            <div class="d-flex align-items-center">
                                <div class="product-review">
                                    <div class="raising-star">
                                        <i class="fa fa-star{% if single_product.average_review < 0.5 %}-o{% elif single_product.average_review >= 0.5 and single_product.average_review < 1 %}-half-o{% endif %}"></i>
                                        <i class="fa fa-star{% if single_product.average_review < 1.5 %}-o{% elif single_product.average_review >= 1.5 and single_product.average_review < 2 %}-half-o{% endif %}"></i>
                                        <i class="fa fa-star{% if single_product.average_review < 2.5 %}-o{% elif single_product.average_review >= 2.5 and single_product.average_review < 3 %}-half-o{% endif %}"></i>
                                        <i class="fa fa-star{% if single_product.average_review < 3.5 %}-o{% elif single_product.average_review >= 3.5 and single_product.average_review < 4 %}-half-o{% endif %}"></i>
                                        <i class="fa fa-star{% if single_product.average_review < 4.5 %}-o{% elif single_product.average_review >= 4.5 and single_product.average_review < 5 %}-half-o{% endif %}"></i>
                                    </div>
                                </div>
                                <a href="#" class="customer-review">{{ single_product.review_count }} Қарау(лар)</a>
                            </div>
                            <div class="price">{{ single_product.price }} {{ request.session.currency }}</div>
                            {% if single_product.stock <= 0 %}
                            <h4 style="color: red" class="title"><i class="fa fa-times" style="color: red"></i> Қоймада жоқ</h4>
                            {% else %}
                            <h4 class="title"><i class="fa fa-check"></i> Қоймада</h4>
                            {% endif %}
                            <p>{{ single_product.description }}</p>
                        </div>

                        <div class="product-details-variable">
                            <h4 class="title">Қолжетімді опциялар</h4>
                            <div class="d-flex align-items-center">
                                <div class="variable-single-item mr-10">
                                    <span>Түс</span>
                                    <select name="color" class="product-variable-size" required>
                                        <option selected> Түсті таңдаңыз</option>
                                        {% for i in single_product.variation_set.colors %}
                                        <option value="{{ i.variation_value }}">{{ i.variation_value }}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                                <div class="variable-single-item">
                                    <span>Өлшем</span>
                                    <select name="size" class="product-variable-size" required>
                                        <option selected> Өлшемді таңдаңыз</option>
                                        {% for i in single_product.variation_set.sizes %}
                                        <option value="{{ i.variation_value }}">{{ i.variation_value }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>

                            <div class="d-flex align-items-center mb-10">
                                {% if single_product.stock <= 0 %}
                                <button style="background: red" class="product-add-to-cart-btnx" disabled>Қоймада жоқ</button>
                                {% else %}
                                <button type="submit" class="product-add-to-cart-btnx mr-10">Себетке қосу</button>
                                {% endif %}
                                <div class="product-add-to-cart-btn">
                                    <a href="{% url 'cart' %}">Себетті қарау</a>
                                </div>
                            </div>
                        </div>

                        <div class="product-details-social">
                            <ul>
                                <li><a href="https://instagram.com/dapperautoparts" class="instagram"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="product-details-content-tab-section section-inner-bg section-top-gap-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="product-details-content-tab-wrapper" data-aos="fade-up" data-aos-delay="0">
                    <div class="product-details-content-tab">
                        <div class="single-tab-content-item">
                            <h5 class="mb-4">Пікірлер</h5>

                            {% if reviews %}
                                {% for review in reviews %}
                                    <div class="single-review mb-4 p-3 border rounded bg-white">
                                        <div class="d-flex justify-content-between">
                                            <strong>{{ review.user.аты_жөні }} {{ review.user.тегі }}</strong>
                                            <small class="text-muted">{{ review.created_at|date:"d.m.Y" }}</small>
                                        </div>
                                        <div class="rating mt-1 mb-2">
                                            {% for i in "12345" %}
                                                {% if forloop.counter <= review.rating %}
                                                    <i class="fa fa-star" style="color:#ea1c26;"></i>
                                                {% else %}
                                                    <i class="fa fa-star-o" style="color:#ccc;"></i>
                                                {% endif %}
                                            {% endfor %}
                                            <span class="ml-2">{{ review.rating }}</span>
                                        </div>
                                        <h6><b>{{ review.subject }}</b></h6>
                                        <p class="mb-1">{{ review.review }}</p>
                                    </div>
                                {% endfor %}
                            {% else %}
                                <p>Бұл өнімге әлі пікір жазылмаған.</p>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}